export const itemList = {
  cakes: [
    {
      img: "/images/cakes/cake1.png",
      alt: "Cake",
      title: "Black Gateu Wedding Cake",
      text: "A luxurious chocolate gateau, perfect for a sophisticated wedding celebration.",
      price: "€250",
    },
    {
      img: "/images/cakes/cake2.jpg",
      alt: "Cake",
      title: "Velvet Deluxe Wedding Cake",
      text: "A rich velvet cake layered with cream cheese frosting, ideal for a grand wedding.",
      price: "€230",
    },
    {
      img: "/images/cakes/cake3.jpg",
      alt: "Cake",
      title: "Elegant Dreams Wedding Cake",
      text: "An elegant wedding cake adorned with delicate floral decorations.",
      price: "€160",
    },
    {
      img: "/images/cakes/cake4.jpg",
      alt: "Cake",
      title: "Vanilla Flower Birthday Cake",
      text: "A classic vanilla cake with a beautiful floral design, perfect for birthdays.",
      price: "€50",
    },
    {
      img: "/images/cakes/cake5.jpg",
      alt: "Cake",
      title: "Carrot Cream Cake",
      text: "A moist carrot cake with cream cheese frosting, offering a delightful taste.",
      price: "€35",
    },
    {
      img: "/images/cakes/cake6.jpg",
      alt: "Cake",
      title: "Fruit Power Forest Cake",
      text: "A fruity forest cake topped with a mix of seasonal fruits and whipped cream.",
      price: "€35",
    },
    {
      img: "/images/cakes/cake7.jpg",
      alt: "Cake",
      title: "Elegant Wisdom Cake",
      text: "An elegant cake with a sophisticated design, ideal for special occasions.",
      price: "€150",
    },
    {
      img: "/images/cakes/cake8.jpg",
      alt: "Cake",
      title: "Blackberry Supreme Cake",
      text: "A rich cake infused with blackberry flavors and topped with a berry compote.",
      price: "€80",
    },
    {
      img: "/images/cakes/cake9.jpg",
      alt: "Cake",
      title: "Queen's Caramel Cake",
      text: "A decadent caramel cake with layers of smooth caramel frosting.",
      price: "€110",
    },
  ],
  pastries: [
    {
      img: "images/pastries/pastry1.jpg",
      alt: "Cheese Pastry with Sesame Seed",
      title: "Cheese Pastry with Sesame Seed",
      text: "A savory pastry filled with creamy cheese and topped with crunchy sesame seeds.",
      price: "€3",
    },
    {
      img: "images/pastries/pastry2.jpg",
      alt: "Croissant",
      title: "Classic Croissant",
      text: "A buttery, flaky croissant, perfect for breakfast or an afternoon snack.",
      price: "€2.5",
    },
    {
      img: "images/pastries/pastry3.jpg",
      alt: "Ham Cheese and Mayo Bun",
      title: "Ham, Cheese, and Mayo Bun",
      text: "A soft bun filled with ham, melted cheese, and a hint of mayo for a savory treat.",
      price: "€3.5",
    },
    {
      img: "images/pastries/pastry4.jpg",
      alt: "Cherry Puff Pastry",
      title: "Cherry Puff Pastry",
      text: "A light and crispy puff pastry filled with sweet cherry filling.",
      price: "€3",
    },
    {
      img: "images/pastries/pastry5.jpg",
      alt: "Cinnamon Bun",
      title: "Cinnamon Bun",
      text: "A soft bun swirled with cinnamon and sugar, topped with a sweet glaze.",
      price: "€2.5",
    },
    {
      img: "images/pastries/pastry6.jpg",
      alt: "Jambon Pastry",
      title: "Jambon",
      text: "A savory puff pastry filled with ham and cheese, baked to golden perfection.",
      price: "€4",
    },
    {
      img: "images/pastries/pastry7.jpg",
      alt: "Macarons",
      title: "Assorted Macarons",
      text: "Delicate French macarons with a variety of flavored fillings.",
      price: "€1.5 ea",
    },
    {
      img: "images/pastries/pastry8.jpg",
      alt: "Pecan Pastry with Glaze",
      title: "Pecan Pastry with Glaze",
      text: "A rich pastry topped with pecans and a sweet caramel glaze.",
      price: "€4",
    },
    {
      img: "images/pastries/pastry9.jpg",
      alt: "Mini Sausage Rolls",
      title: "Mini Sausage Rolls",
      text: "Flaky puff pastry wrapped around seasoned sausage for a savory snack.",
      price: "€5",
    },
  ],
  doughnuts: [
    {
      img: "/images/cake1.png",
      alt: "Cake",
      title: "Black Gateu Wedding Cake",
      text: "A luxurious chocolate gateau, perfect for a sophisticated wedding celebration.",
      price: "€250",
    },
  ],
  cookies: [
    {
      img: "/images/cake1.png",
      alt: "Cake",
      title: "Black Gateu Wedding Cake",
      text: "A luxurious chocolate gateau, perfect for a sophisticated wedding celebration.",
      price: "€250",
    },
    {
      img: "/images/cake1.png",
      alt: "Cake",
      title: "Black Gateu Wedding Cake",
      text: "A luxurious chocolate gateau, perfect for a sophisticated wedding celebration.",
      price: "€250",
    },
  ],
};
